// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Muhasebe.Data.DataContext;

#nullable disable

namespace Muhasebe.Data.Migrations
{
    [DbContext(typeof(AppSistemDbContext))]
    partial class AppSistemDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.8");

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.AppVersiyon", b =>
                {
                    b.Property<string>("Versiyon")
                        .HasColumnType("TEXT");

                    b.HasKey("Versiyon");

                    b.ToTable("AppVersiyon");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.DbYedekAl", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DonemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("SonrakiYedekTarih")
                        .HasColumnType("TEXT");

                    b.Property<string>("YedeklemeAraligi")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<TimeSpan>("YedeklemeSaati")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DbYedekAl");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.Degerler", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.Property<long>("SonSecilenDonem")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SonSecilenKullanici")
                        .HasColumnType("INTEGER");

                    b.Property<long>("SonSecilenSirket")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("Degerler");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.DevirLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevirNotu")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HedefDonem")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KaynakDonem")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("Moduller")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.Property<long>("SirketId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SirketKisaUnvan")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SirketTamUnvan")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("Tarih")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DevirLog");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.DevirLogII", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("A1")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("A2")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("A3")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("A4")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DevirAciklama")
                        .IsRequired()
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<int>("DevirYili")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("DevirLogII");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.DonemDBSec", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("DBName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("DBPath")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("TEXT");

                    b.Property<int>("DatabaseType")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Directory")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long>("MaliDonemId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("MaliDonemId")
                        .IsUnique();

                    b.ToTable("DonemDBSec");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.Firma", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adres")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eposta")
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Il")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Ilce")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KisaUnvani")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("Logo")
                        .HasColumnType("BLOB");

                    b.Property<byte[]>("LogoOnizleme")
                        .HasColumnType("BLOB");

                    b.Property<string>("PBu1")
                        .IsRequired()
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PBu2")
                        .HasMaxLength(10)
                        .HasColumnType("TEXT");

                    b.Property<string>("PostaKodu")
                        .HasMaxLength(25)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.Property<string>("TCNo")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("TamUnvani")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon1")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon2")
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiDairesi")
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("VergiNo")
                        .HasMaxLength(11)
                        .HasColumnType("TEXT");

                    b.Property<string>("Web")
                        .HasMaxLength(75)
                        .HasColumnType("TEXT");

                    b.Property<string>("YetkiliKisi")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Firmalar");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.Hesap", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<long>("DonemId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("SonGirisTarihi")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("KullaniciId");

                    b.ToTable("Hesaplar");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.Kullanici", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Adi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Eposta")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("KullaniciAdi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Rol")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.Property<string>("SifreHash")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("Soyadi")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(17)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Kullanicilar");

                    b.HasData(
                        new
                        {
                            Id = 241341L,
                            Adi = "Ömer",
                            AktifMi = true,
                            Eposta = "korkutomer@gmail.com",
                            KaydedenId = 5413300800L,
                            KayitTarihi = new DateTimeOffset(new DateTime(2025, 3, 12, 0, 0, 0, 0, DateTimeKind.Unspecified), new TimeSpan(0, 3, 0, 0, 0)),
                            KullaniciAdi = "korkutomer",
                            Rol = "Yönetici",
                            SearchTerms = "korkutomer, Ömer Korkut, Yönetici",
                            SifreHash = "AQAAAAIAAYagAAAAECnYdlrjFiWFJc+FGeGDmvR87uz20oU/Z0K4JE9ddoF2VUnmHw0idEFX8UPOb4cpzQ==",
                            Soyadi = "Korkut",
                            Telefon = "0 (541) 330 0800"
                        });
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.MaliDonem", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<long>("FirmaId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<int>("MaliDonemler")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("FirmaId");

                    b.ToTable("CalismaDonemler");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.ModulSec", b =>
                {
                    b.Property<long>("KullaniciId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ajanda_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ajanda_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ajanda_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ajanda_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ayarlar_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ayarlar_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ayarlar_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_ayarlar_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_banka_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_banka_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_banka_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_banka_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cari_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cari_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cari_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cari_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cek_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cek_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cek_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_cek_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_hatirlatma_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_hatirlatma_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_hatirlatma_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_hatirlatma_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_istatistikler_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_istatistikler_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_istatistikler_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_istatistikler_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_kasa_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_kasa_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_kasa_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_kasa_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_personel_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_personel_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_personel_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_personel_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_raporlar_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_raporlar_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_raporlar_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_raporlar_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_senet_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_senet_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_senet_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_senet_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_siparis_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_siparis_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_siparis_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_siparis_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_stok_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_stok_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_stok_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_stok_y4")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_teklif_y1")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_teklif_y2")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_teklif_y3")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("mdl_teklif_y4")
                        .HasColumnType("INTEGER");

                    b.HasKey("KullaniciId");

                    b.ToTable("ModulSecim");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.UpdateSettings", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoCheckOnStartup")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoDownload")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("AutoInstall")
                        .HasColumnType("INTEGER");

                    b.Property<int>("CheckIntervalHours")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IncludeBetaVersions")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("LastCheckDate")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingUpdateDownloadUrl")
                        .HasColumnType("TEXT");

                    b.Property<DateTime?>("PendingUpdateDownloadedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingUpdateFileHash")
                        .HasColumnType("TEXT");

                    b.Property<long>("PendingUpdateFileSize")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PendingUpdateLocalPath")
                        .HasColumnType("TEXT");

                    b.Property<string>("PendingUpdateVersion")
                        .HasColumnType("TEXT");

                    b.Property<bool>("ShowNotifications")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UpdateChannel")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("UpdateSettings");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.Uygulama.AppLog", b =>
                {
                    b.Property<long>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<bool>("AktifMi")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Description")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("GuncellemeTarihi")
                        .HasColumnType("TEXT");

                    b.Property<long?>("GuncelleyenId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsRead")
                        .HasColumnType("INTEGER");

                    b.Property<long>("KaydedenId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("KayitTarihi")
                        .HasColumnType("TEXT");

                    b.Property<string>("Message")
                        .IsRequired()
                        .HasMaxLength(400)
                        .HasColumnType("TEXT");

                    b.Property<string>("SearchTerms")
                        .HasColumnType("TEXT");

                    b.Property<string>("Source")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.Property<int>("Type")
                        .HasColumnType("INTEGER");

                    b.Property<string>("User")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("AppLogs");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.DonemDBSec", b =>
                {
                    b.HasOne("Muhasebe.Domain.Entities.SistemDb.MaliDonem", "MaliDonem")
                        .WithOne("DonemDBSec")
                        .HasForeignKey("Muhasebe.Domain.Entities.SistemDb.DonemDBSec", "MaliDonemId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("MaliDonem");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.Hesap", b =>
                {
                    b.HasOne("Muhasebe.Domain.Entities.SistemDb.Kullanici", "Kullanici")
                        .WithMany("Hesaplar")
                        .HasForeignKey("KullaniciId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Kullanici");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.MaliDonem", b =>
                {
                    b.HasOne("Muhasebe.Domain.Entities.SistemDb.Firma", "Firma")
                        .WithMany("MaliDonemler")
                        .HasForeignKey("FirmaId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Firma");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.Firma", b =>
                {
                    b.Navigation("MaliDonemler");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.Kullanici", b =>
                {
                    b.Navigation("Hesaplar");
                });

            modelBuilder.Entity("Muhasebe.Domain.Entities.SistemDb.MaliDonem", b =>
                {
                    b.Navigation("DonemDBSec")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
