name: WinUI3 Release - MuhasibPro (Fixed .NET Version)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Version (e.g., 1.0.0)'
        required: false
        type: string
  push:
    tags:
      - "v*"

env:
  PROJECT_PATH: MuhasibPro/MuhasibPro.csproj
  SOLUTION_PATH: MuhasibPro.sln
  APP_NAME: MuhasibPro
  DOTNET_VERSION: '8.0.407'

jobs:
  release:
    runs-on: windows-2022

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Setup .NET 8.0.407
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: ${{ env.DOTNET_VERSION }}

      - name: Check .NET Version
        run: |
          dotnet --version
          dotnet --list-sdks

      # MSBuild yolunu bul ve PATH'e ekle
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2      

      - name: Restore packages
        run: |
         dotnet restore "${{ env.SOLUTION_PATH }}" `
         -p:Platform=x64 `
         --verbosity normal


      - name: Build solution
        run: |
         msbuild "${{ env.SOLUTION_PATH }}" `
         /p:Configuration=Release `
         /p:Platform=x64 `
         /p:TargetFramework=net8.0-windows10.0.26100.0 `
         /p:WindowsPackageType=None `
         /verbosity:minimal `
         /nologo

      - name: Publish with EXACT VS2022 Settings
        run: |
          Write-Host "Publishing with EXACT VS2022 settings..."          
          $publishPath = "publish-win-x64"
          $absolutePublishPath = Join-Path $env:GITHUB_WORKSPACE $publishPath
      
          if (Test-Path $publishPath) {
            Remove-Item $publishPath -Recurse -Force
          }
          New-Item -ItemType Directory -Path $publishPath -Force | Out-Null
      
          # MSBuild veya dotnet msbuild kullan
          if (Test-Path env:MSBUILD_PATH) {
            msbuild "${{ env.PROJECT_PATH }}" `
              /t:Publish `
              /p:Configuration=Release `
              /p:Platform=x64 `
              /p:RuntimeIdentifier=win-x64 `
              /p:SelfContained=true `
              /p:PublishDir="$absolutePublishPath" `
              /p:WindowsAppSdkSelfContained=true `
              /p:WindowsPackageType=None `
              /p:GenerateLibraryLayout=true `
              /p:PublishReadyToRun=false `
              /p:PublishSingleFile=false `
              /p:PublishTrimmed=false `
              /p:TargetFramework=net8.0-windows10.0.26100.0 `
              /p:UseCurrentRuntimeIdentifier=true `
              /p:CopyOutputSymbolsToPublishDirectory=false `
              /verbosity:minimal `
              /nologo
          } else {
            dotnet msbuild "${{ env.PROJECT_PATH }}" `
              /t:Publish `
              /p:Configuration=Release `
              /p:Platform=x64 `
              /p:RuntimeIdentifier=win-x64 `
              /p:SelfContained=true `
              /p:PublishDir="$absolutePublishPath" `
              /p:WindowsAppSdkSelfContained=true `
              /p:WindowsPackageType=None `
              /p:GenerateLibraryLayout=true `
              /p:PublishReadyToRun=false `
              /p:PublishSingleFile=false `
              /p:PublishTrimmed=false `
              /p:TargetFramework=net8.0-windows10.0.26100.0 `
              /p:UseCurrentRuntimeIdentifier=true `
              /p:CopyOutputSymbolsToPublishDirectory=false `
              /verbosity:minimal `
              /nologo
          }
      
          if ($LASTEXITCODE -ne 0) {
            Write-Host "Publish failed with exit code: $LASTEXITCODE"
            exit 1
          }
          
          # Validation
          $mainExe = Join-Path $publishPath "${{ env.APP_NAME }}.exe"
          if (Test-Path $mainExe) {
            $exeSize = (Get-Item $mainExe).Length / 1MB
            $fileCount = (Get-ChildItem $publishPath -File).Count
            Write-Host "Published: $([math]::Round($exeSize, 2)) MB EXE, $fileCount files"
          }

      - name: Fix PRI file for Velopack compatibility
        run: |
          $publishPath = "publish-win-x64"
          $appPriFile = Join-Path $publishPath "${{ env.APP_NAME }}.pri"
          $resourcesPriFile = Join-Path $publishPath "resources.pri"
          
          Write-Host "Fixing PRI file naming for Velopack compatibility..."
          
          # Yeni WinUI3 SDK'sı uygulamaAdi.pri oluşturur, Velopack resources.pri bekler
          if (Test-Path $appPriFile) {
            Write-Host "✓ ${{ env.APP_NAME }}.pri found (new WinUI3 SDK format)"
            
            # resources.pri dosyasını oluştur (kopyala)
            Copy-Item $appPriFile $resourcesPriFile -Force
            Write-Host "✓ Created resources.pri from ${{ env.APP_NAME }}.pri for Velopack"
            
            # Her iki dosyanın da var olduğunu doğrula
            if (Test-Path $resourcesPriFile) {
              Write-Host "✓ Both PRI files are ready: ${{ env.APP_NAME }}.pri and resources.pri"
            }
          } elseif (Test-Path $resourcesPriFile) {
            Write-Host "✓ resources.pri found (legacy format)"
          } else {
            Write-Host "⚠ WARNING: No PRI file found in publish directory"
            Write-Host "Available files:"
            Get-ChildItem $publishPath -Name | Sort-Object
          }

      - name: Verify Published Files
        run: |
          $publishPath = "publish-win-x64"
          Write-Host "Published file structure:"
          Get-ChildItem $publishPath -Recurse | Select-Object Name, Length | Format-Table -AutoSize
          
          # Kritik dosya boyutlarını kontrol et
          $exePath = Join-Path $publishPath "${{ env.APP_NAME }}.exe"
          if (Test-Path $exePath) {
            $exeSize = (Get-Item $exePath).Length / 1MB
            Write-Host "Main EXE size: $([math]::Round($exeSize, 2)) MB"
          }
          
          # PRI dosyalarını kontrol et
          $appPriFile = Join-Path $publishPath "${{ env.APP_NAME }}.pri"
          $resourcesPriFile = Join-Path $publishPath "resources.pri"
          
          if (Test-Path $appPriFile) {
            $appPriSize = (Get-Item $appPriFile).Length / 1KB
            Write-Host "${{ env.APP_NAME }}.pri size: $([math]::Round($appPriSize, 2)) KB"
          }
          
          if (Test-Path $resourcesPriFile) {
            $resourcesPriSize = (Get-Item $resourcesPriFile).Length / 1KB
            Write-Host "resources.pri size: $([math]::Round($resourcesPriSize, 2)) KB"
          }

      # Version bilgisini al
      - name: Extract version from tag
        id: version
        run: |
          if ("${{ github.event.inputs.version }}" -ne "") {
            $version = "${{ github.event.inputs.version }}"
          } else {
            $tag = "${{ github.ref }}"
            $version = $tag -replace "refs/tags/v", ""
          }
          echo "version=$version" >> $env:GITHUB_OUTPUT
          echo "tag_name=v$version" >> $env:GITHUB_OUTPUT
          Write-Host "Version: $version"

      - name: Get latest Velopack CLI version
        id: get_vpk_version
        run: |
          $response = Invoke-RestMethod -Uri "https://api.nuget.org/v3-flatcontainer/vpk/index.json"
          $latestVersion = $response.versions[-1]
          echo "vpk_version=$latestVersion" >> $env:GITHUB_OUTPUT

      - name: Install Velopack CLI
        run: |
          dotnet tool install -g vpk --version ${{ steps.get_vpk_version.outputs.vpk_version }}

      - name: Generate release notes
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $buildDate = Get-Date -Format "dd.MM.yyyy HH:mm"
          $notes = @"
          # MuhasibPro v$version
          ## Sürüm Bilgileri
          - **Sürüm:** $version
          - **Derleme Tarihi:** $buildDate
          - **Platform:** Windows 10/11 (x64)
          - **UI Framework:** WinUI 3
          "@
          $notes | Out-File -FilePath "RELEASE_NOTES.md" -Encoding UTF8

      - name: Create Velopack package
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $publishPath = "publish-win-x64"
          $outputDir = "releases"
          New-Item -ItemType Directory -Path $outputDir -Force | Out-Null
          
          # Velopack için resources.pri'nin var olduğunu tekrar kontrol et
          $resourcesPriFile = Join-Path $publishPath "resources.pri"
          if (-not (Test-Path $resourcesPriFile)) {
            Write-Host "⚠ WARNING: resources.pri not found, checking for ${{ env.APP_NAME }}.pri"
            $appPriFile = Join-Path $publishPath "${{ env.APP_NAME }}.pri"
            if (Test-Path $appPriFile) {
              Write-Host "Creating resources.pri from ${{ env.APP_NAME }}.pri"
              Copy-Item $appPriFile $resourcesPriFile -Force
            }
          }
    
          Write-Host "Creating Velopack package..."
          vpk pack `
            --packId "${{ env.APP_NAME }}" `
            --packVersion "$version" `
            --packDir "$publishPath" `
            --outputDir "$outputDir" `
            --mainExe "${{ env.APP_NAME }}.exe" `
            --packTitle "MuhasibPro" `
            --packAuthors "MuhasibPro Team" `
            --releaseNotes "./RELEASE_NOTES.md"

      - name: Create portable ZIP
        run: |
          $version = "${{ steps.version.outputs.version }}"
          $zipName = "${{ env.APP_NAME }}-v$version-portable-win-x64.zip"
          $zipPath = Join-Path "releases" $zipName
          Compress-Archive -Path "publish-win-x64/*" -DestinationPath $zipPath -Force

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          name: "MuhasibPro v${{ steps.version.outputs.version }}"
          body_path: RELEASE_NOTES.md
          draft: false
          prerelease: false
          token: ${{ secrets.GITHUB_TOKEN }}
          files: |
            releases/*.vpk
            releases/*.zip

      - name: Upload release artifacts
        uses: actions/upload-artifact@v4
        with:
          name: muhasibpro-v${{ steps.version.outputs.version }}-release
          path: |
            releases/*
            RELEASE_NOTES.md
          retention-days: 30
